### ISSUE TITLE
template.rb

### ISSUE THREAD

**Issue by ghost** [TIY-DC-ROR-2015-Jan/rails-template#4]
Bundle will not recognize "gem_group"
gsub_file not defined.

**Comment by jamesdabbs** [comment]
I'm not sure what you mean. What are you running that produces this error?

**Comment by ghost** [comment]
Umm. Looks like I'm not running the setup correctly. How should I have run it? I began with a new rails installation. Moved the template.rb into the directory and tried running that from rails/ruby. I googled gsub_file but couldn't find anything. When I did the bundle install is when it complained it didn't understand 'gem_group'.

**Comment by jamesdabbs** [comment]
Oh, I see. Yeah, you want to tell Rails to use the template while you're doing `rails new`; it's not a file you pull in later. See [the README](https://github.com/TIY-DC-ROR-2015-Jan/rails-template#rails-template) for the exact command.

**Comment by ghost** [comment]
No, no. I SEE. Got it. I thought the script would be pulled down… and you know. But it’s run parallel with the creation of the project. Didn’t connect with that. Thanks, JD.

David Livingston
