### ISSUE TITLE
Autoload lib folder?

### ISSUE THREAD

**Issue by kwals** [TIY-DC-ROR-2015-Jan/rails-template#5]
Would we use the autoload lib folder function enough to want to add it to the template? Perhaps like HTTParty, ask if they want to include it? 

Put this into the config/application.rb ?

config.autoload_paths << Rails.root.join('lib')

**Comment by jamesdabbs** [comment]
Ask is a good call. I don't want y'all to start relying on that and then be
baffled when it isn't working on whatever app you look at on the job the
first time, so something to remind you would be good. (Also it does slow
down boot up just a tad, so some people might want to opt out.)

**Comment by kwals** [comment]
This code is overwriting the whole file - how can I get it to just add the line to the file?

`if yes? "Would you like the Lib folder to autoload? y/n"
    file "config/application.rb", <<-CODE
  config.autoload_paths << Rails.root.join('lib')
    CODE
end`
